services:
  yaf:
    build: ./yaf
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - super_mediator

  super_mediator:
    build: ./super_mediator
    restart: always
    network_mode: host
#    depends_on:
#      - nfdump
#      - silk

  nfdump:
    build: ./nfdump
    restart: always
    ports:
      - 8888:8888/udp

  goflow:
    build: ./goflow
    restart: always
    ports:
      - 2055:2055/udp
    depends_on:
      - broker

  maltrail:
    build: ./maltrail
    restart: always
    ports:
      - "19000-19100:19000-19100"
      - "19000-19100:19000-19100/udp"
    volumes:
      - maltrail:/root/.maltrail

  silk:
    build: ./SiLK
    restart: always
    ports:
      - 7777:7777

  graylog:
    build: ./graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000  
      - 9999:9999/udp


  elasticsearch:
    image: elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
  
  mongo:
    image: mongo:6.0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - 8080:8080
  
  broker:
    image: apache/kafka:3.7.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

volumes:
  graylog:
  maltrail:

#sudo docker compose up yaf super_mediator broker kafka-ui goflow --build
