services:
  yaf:
    build: ./yaf
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - super_mediator

  super_mediator:
    build: ./super_mediator
    restart: always
    network_mode: host
    depends_on:
      - graylog
      - nfdump
      - silk

  nfdump:
    build: ./nfdump
    restart: always
    ports:
      - 8888:8888/udp

  silk:
    build: ./SiLK
    restart: always
    ports:
      - 7777:7777

  graylog:
    build: ./graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000  
      - 9999:9999/udp


  elasticsearch:
    image: elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
  
  mongo:
    image: mongo:6.0

